// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", undefined);
}

var make = App;

var $$default = App;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
