// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Graphql$FragmentExperiment from "./Graphql.bs.js";

function App(Props) {
  var queryResult = Curry.app(Graphql$FragmentExperiment.Fruits.use, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      ]);
  var match = queryResult.data;
  if (match === undefined) {
    return "Data loading or failed";
  }
  var fruits = match.fruits;
  if (fruits !== undefined) {
    return React.createElement("ul", undefined, Belt_Array.map(fruits, (function (fruit) {
                      if (fruit === undefined) {
                        return null;
                      }
                      var id = fruit.id;
                      if (id === undefined) {
                        return null;
                      }
                      var name = fruit.fruit_name;
                      if (name !== undefined) {
                        return React.createElement("li", {
                                    key: id
                                  }, name);
                      } else {
                        return null;
                      }
                    })));
  } else {
    return "Data loading or failed";
  }
}

var make = App;

var $$default = App;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
