// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApolloClient__React_Hooks_UseQuery from "rescript-apollo-client/src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.bs.js";

var Raw = {};

var query = (require("@apollo/client").gql`
  fragment ProducingCountries on countries   {
    __typename
    country
  }
`);

function parse(value) {
  var value$1 = value.country;
  return {
          __typename: value.__typename,
          country: !(value$1 == null) ? value$1 : undefined
        };
}

function serialize(value) {
  var value$1 = value.country;
  var country = value$1 !== undefined ? value$1 : null;
  var value$2 = value.__typename;
  return {
          __typename: value$2,
          country: country
        };
}

function verifyArgsAndParse(_ProducingCountries, value) {
  return parse(value);
}

function verifyName(param) {
  
}

var ProducingCountries = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  verifyArgsAndParse: verifyArgsAndParse,
  verifyName: verifyName
};

var Raw$1 = {};

var query$1 = (require("@apollo/client").gql`
  fragment OtherFruitFields on Fruits   {
    __typename
    family
  }
`);

function parse$1(value) {
  var value$1 = value.family;
  return {
          __typename: value.__typename,
          family: !(value$1 == null) ? value$1 : undefined
        };
}

function serialize$1(value) {
  var value$1 = value.family;
  var family = value$1 !== undefined ? value$1 : null;
  var value$2 = value.__typename;
  return {
          __typename: value$2,
          family: family
        };
}

function verifyArgsAndParse$1(_OtherFruitFields, value) {
  return parse$1(value);
}

function verifyName$1(param) {
  
}

var OtherFruitFields = {
  Raw: Raw$1,
  query: query$1,
  parse: parse$1,
  serialize: serialize$1,
  verifyArgsAndParse: verifyArgsAndParse$1,
  verifyName: verifyName$1
};

var Raw$2 = {};

var query$2 = ((frag_0) => require("@apollo/client").gql`
  query Fruits  {
    fruits  {
      __typename
      id
      fruit_name
      producing_countries  {
        ...ProducingCountries
      }
    }
  }
  ${frag_0}
`)(query);

function parse$2(value) {
  var value$1 = value.fruits;
  return {
          fruits: !(value$1 == null) ? value$1.map(function (value) {
                  if (value == null) {
                    return ;
                  }
                  var value$1 = value.id;
                  var value$2 = value.fruit_name;
                  var value$3 = value.producing_countries;
                  return {
                          __typename: value.__typename,
                          id: !(value$1 == null) ? value$1 : undefined,
                          fruit_name: !(value$2 == null) ? value$2 : undefined,
                          producing_countries: !(value$3 == null) ? value$3.map(function (value) {
                                  if (!(value == null)) {
                                    return parse(value);
                                  }
                                  
                                }) : undefined
                        };
                }) : undefined
        };
}

function serialize$2(value) {
  var value$1 = value.fruits;
  var fruits = value$1 !== undefined ? value$1.map(function (value) {
          if (value === undefined) {
            return null;
          }
          var value$1 = value.producing_countries;
          var producing_countries = value$1 !== undefined ? value$1.map(function (value) {
                  if (value !== undefined) {
                    return serialize(value);
                  } else {
                    return null;
                  }
                }) : null;
          var value$2 = value.fruit_name;
          var fruit_name = value$2 !== undefined ? value$2 : null;
          var value$3 = value.id;
          var id = value$3 !== undefined ? value$3 : null;
          var value$4 = value.__typename;
          return {
                  __typename: value$4,
                  id: id,
                  fruit_name: fruit_name,
                  producing_countries: producing_countries
                };
        }) : null;
  return {
          fruits: fruits
        };
}

function serializeVariables(param) {
  
}

function makeVariables(param) {
  
}

function makeDefaultVariables(param) {
  
}

var Fruits_inner = {
  Raw: Raw$2,
  query: query$2,
  parse: parse$2,
  serialize: serialize$2,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables
};

var include = ApolloClient__React_Hooks_UseQuery.Extend({
      query: query$2,
      Raw: Raw$2,
      parse: parse$2,
      serialize: serialize$2,
      serializeVariables: serializeVariables
    });

var Fruits_refetchQueryDescription = include.refetchQueryDescription;

var Fruits_use = include.use;

var Fruits_useLazy = include.useLazy;

var Fruits_useLazyWithVariables = include.useLazyWithVariables;

var Fruits = {
  Fruits_inner: Fruits_inner,
  Raw: Raw$2,
  query: query$2,
  parse: parse$2,
  serialize: serialize$2,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables,
  refetchQueryDescription: Fruits_refetchQueryDescription,
  use: Fruits_use,
  useLazy: Fruits_useLazy,
  useLazyWithVariables: Fruits_useLazyWithVariables
};

export {
  ProducingCountries ,
  OtherFruitFields ,
  Fruits ,
  
}
/* query Not a pure module */
