// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApolloClient__React_Hooks_UseQuery from "rescript-apollo-client/src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.bs.js";

function deepMerge(json, param) {
  return json;
}

var GraphQL_PPX = {
  deepMerge: deepMerge
};

var Raw = {};

var query = (require("@apollo/client").gql`
  fragment OtherFruitFields on Fruits   {
    __typename
    family
  }
`);

function parse(value) {
  var value$1 = value.family;
  return {
          __typename: value.__typename,
          family: !(value$1 == null) ? value$1 : undefined
        };
}

function serialize(value) {
  var value$1 = value.family;
  var family = value$1 !== undefined ? value$1 : null;
  var value$2 = value.__typename;
  return {
          __typename: value$2,
          family: family
        };
}

function verifyArgsAndParse(_OtherFruitFields, value) {
  return parse(value);
}

function verifyName(param) {
  
}

var OtherFruitFields = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  verifyArgsAndParse: verifyArgsAndParse,
  verifyName: verifyName
};

var Raw$1 = {};

var query$1 = ((frag_0) => require("@apollo/client").gql`
  query Fruits  {
    fruits  {
      __typename
      id
      fruit_name
      ...OtherFruitFields
    }
  }
  ${frag_0}
`)(query);

function parse$1(value) {
  var value$1 = value.fruits;
  return {
          fruits: !(value$1 == null) ? value$1.map(function (value) {
                  if (value == null) {
                    return ;
                  }
                  var value$1 = value["id"];
                  var value$2 = value["fruit_name"];
                  return {
                          __typename: value["__typename"],
                          id: !(value$1 == null) ? value$1 : undefined,
                          fruit_name: !(value$2 == null) ? value$2 : undefined,
                          otherFruitFields: parse(value)
                        };
                }) : undefined
        };
}

function serialize$1(value) {
  var value$1 = value.fruits;
  var fruits = value$1 !== undefined ? value$1.map(function (value) {
          if (value === undefined) {
            return null;
          }
          var value$1 = value.fruit_name;
          var fruit_name = value$1 !== undefined ? value$1 : null;
          var value$2 = value.id;
          var id = value$2 !== undefined ? value$2 : null;
          var value$3 = value.__typename;
          return [serialize(value.otherFruitFields)].reduce(deepMerge, {
                      __typename: value$3,
                      id: id,
                      fruit_name: fruit_name
                    });
        }) : null;
  return {
          fruits: fruits
        };
}

function serializeVariables(param) {
  
}

function makeVariables(param) {
  
}

function makeDefaultVariables(param) {
  
}

var Fruits_inner = {
  Raw: Raw$1,
  query: query$1,
  parse: parse$1,
  serialize: serialize$1,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables
};

var include = ApolloClient__React_Hooks_UseQuery.Extend({
      query: query$1,
      Raw: Raw$1,
      parse: parse$1,
      serialize: serialize$1,
      serializeVariables: serializeVariables
    });

var Fruits_refetchQueryDescription = include.refetchQueryDescription;

var Fruits_use = include.use;

var Fruits_useLazy = include.useLazy;

var Fruits_useLazyWithVariables = include.useLazyWithVariables;

var Fruits = {
  Fruits_inner: Fruits_inner,
  Raw: Raw$1,
  query: query$1,
  parse: parse$1,
  serialize: serialize$1,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables,
  refetchQueryDescription: Fruits_refetchQueryDescription,
  use: Fruits_use,
  useLazy: Fruits_useLazy,
  useLazyWithVariables: Fruits_useLazyWithVariables
};

export {
  GraphQL_PPX ,
  OtherFruitFields ,
  Fruits ,
  
}
/* query Not a pure module */
